from Grafy import *

print("Graf nieskierowany:")
G = GrafNieskierowany()
G.dodaj_wierzcholek(1)
G.dodaj_wierzcholek(2)
G.dodaj_wierzcholek(3)
G.dodaj_wierzcholek(4)
G.dodaj_wierzcholek(5)
G.dodaj_krawedz(1, 2)
G.dodaj_krawedz(1, 3)
G.dodaj_krawedz(1, 4)
G.dodaj_krawedz(3, 2)
G.wypisz()
print("")
G.usun_krawedz(3, 2)
G.wypisz()
print("")
G.dodaj_krawedz(1, 5)
G.wypisz()
print("")

print("Graf skierowany:")

G = GrafSkierowany()
G.dodaj_wierzcholek(1)
G.dodaj_wierzcholek(2)
G.dodaj_wierzcholek(3)
G.dodaj_wierzcholek(4)
G.dodaj_wierzcholek(5)
G.dodaj_krawedz(1, 2)
G.dodaj_krawedz(1, 3)
G.dodaj_krawedz(1, 4)
G.dodaj_krawedz(3, 2)
G.wypisz()
print("")
G.usun_krawedz(3, 2)
G.wypisz()
print("")
G.dodaj_krawedz(1, 5)
G.wypisz()
